insert into team (name) values ('woowa')
insert into team (name) values ('bros')

insert into member (name, age, team_id) values ('lavine', 26, 1)
insert into member (name, age, team_id) values ('pobi', 50, 1)
insert into member (name, age, team_id) values ('json', 29, 1)
insert into member (name, age, team_id) values ('brown', 33, 1)
insert into member (name, age, team_id) values ('jun', 31, 2)
insert into member (name, age, team_id) values ('cu', 35, 2)
insert into member (name, age, team_id) values ('woni', 30, 2)